/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElText: typeof import('element-plus/es')['ElText']
    FileComponent: typeof import('./src/components/file/FileComponent.vue')['default']
    FolderComponent: typeof import('./src/components/file/FolderComponent.vue')['default']
    FolderPagination: typeof import('./src/components/file/FolderPagination.vue')['default']
    InviteCodeDialog: typeof import('./src/components/InviteCodeDialog.vue')['default']
    LoginRegisterDialog: typeof import('./src/components/LoginRegisterDialog.vue')['default']
    RawFileComponent: typeof import('./src/components/RawFileComponent.vue')['default']
    SingleFileProgress: typeof import('./src/components/upload/SingleFileProgress.vue')['default']
    SingleRawFileComponent: typeof import('./src/components/file/SingleRawFileComponent.vue')['default']
    UploadDialog: typeof import('./src/components/upload/UploadDialog.vue')['default']
    UserSettingsDialog: typeof import('./src/components/UserSettingsDialog.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
