name: "编译"
on:
  push:
    branches:
      - master
      - ci
  workflow_dispatch:
jobs:
  Building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'gradle'
      - run: gradle bootJar