name: "编译"
on:
  push:
    branches:
      - master
      - ci
  workflow_dispatch:
jobs:
  Building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Build With Gradle
        run: ./gradlew bootJar