name: "编译"
on:
  push:
    branches:
      - master
      - ci
  workflow_dispatch:
jobs:
  Building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Gradle init script for mirrors
        run: echo "allprojects { repositories { maven { url 'https://maven.aliyun.com/repository/public/' } maven { url 'https://maven.aliyun.com/repository/google/' } maven { url 'https://maven.aliyun.com/repository/gradle-plugin/' } maven { url 'https://mirrors.huaweicloud.com/repository/maven/' } mavenCentral() } } buildscript { repositories { maven { url 'https://maven.aliyun.com/repository/public/' } maven { url 'https://maven.aliyun.com/repository/gradle-plugin/' } } }" > ~/.gradle/init.gradle
      - name: Cache Gradle files
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup Executable Permission
        run: chmod +x gradlew
      - name: Build With Gradle
        run: ./gradlew bootJar --no-daemon --parallel --build-cache --no-scan