name: "编译"
on:
  push:
    branches:
      - master
      - ci
  workflow_dispatch:
jobs:
  Building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set HTTP Proxy
        run: |
          mkdir -p ~/.gradle
          echo "systemProp.http.proxyHost=192.168.5.6" >> ~/.gradle/gradle.properties
          echo "systemProp.http.proxyPort=7890" >> ~/.gradle/gradle.properties
          echo "systemProp.https.proxyHost=192.168.5.6" >> ~/.gradle/gradle.properties
          echo "systemProp.https.proxyPort=7890" >> ~/.gradle/gradle.properties
      - name: Cache Gradle files
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup Executable Permission
        run: chmod +x gradlew
      - name: Build With Gradle
        run: ./gradlew bootJar --no-daemon --parallel --build-cache --no-scan
      - uses: actions/upload-artifact@v4
        with:
          name: "FMV2.jar"
          path: build/libs/FileManager-0.0.1-SNAPSHOT.jar